.TH dhcp-stats 1
.SH NAME
dhcp-stats \- DHCP traffic analyzer
.SH SYNOPSIS
.B dhcp-stats
[\fB\-i\fR \fI<interface>\fR]
[\fB\-r\fR \fI<filename>\fR]
\fI<ip-prefix>\fR
[\fI<ip-prefix>\fR [\fB...\fR]]
.SH DESCRIPTION
.B dhcp-stats
monitors DHCP traffic on a network and supplies statistical information about the utilization of IP addresses for given IP prefixes
.SH OPTIONS
.TP
.BR \-i
Set the interface on which the analyzer should listen
.TP
.BR \-r
Supply pcap file to analyze
.SH AUTHOR
Tereza Kubincova (xkubin27@stud.fit.vutbr.cz)
